server:
  port: 80
  tomcat:
    uri-encoding: utf-8

spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  application:
    name: cloud-order-service
  zipkin:
    sleuth:
      samper:
        probablitiy: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true