server:
  port: 80
  tomcat:
    uri-encoding: utf-8

spring:
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      # 注册到zookeeper地址
      connect-string: 47.111.77.3:2181