server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/lyszlj/cloud2020-config.git
          search-paths:
            - springcloud-config
          username: lyszlj
          password: hm517060
      label: master

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

